#!/bin/bash


#make all

printf 'list as no barrier, barrier\n'

printf '' > result.txt

for i in {1..100}
do
	
	
#	mpirun -np 1 ./CLA t0.txt a		>> result.txt
#	mpirun -np 1 ./CLAB t0.txt a	>> result.txt

	./CLA1 < t0.txt >> result.txt
	./CLA1 < t0.txt >> result.txt

	mpirun -np 2 ./CLA t0.txt a		>> result.txt
	mpirun -np 2 ./CLAB t0.txt a	>> result.txt
	
	mpirun -np 4 ./CLA t0.txt a		>> result.txt
	mpirun -np 4 ./CLAB t0.txt a	>> result.txt
	
	mpirun -np 8 ./CLA t0.txt a		>> result.txt
	mpirun -np 8 ./CLAB t0.txt a	>> result.txt
	
	mpirun -np 16 ./CLA t0.txt a	>> result.txt
	mpirun -np 16 ./CLAB t0.txt a	>> result.txt
	
	mpirun -np 32 ./CLA t0.txt a	>> result.txt
	mpirun -np 32 ./CLAB t0.txt a	>> result.txt
	
	printf "\n" >> result.txt 

	if [ $i -gt 100 ]; then
		printf "\033[3D%d" $i
	elif [ $i -gt 10 ]; then
		printf "\033[2D%d" $i
	else
		printf "\033[1D%d" $i
	fi

done

printf "\n"
